name: Trigger auto deployment for democontainerappgithub

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/democontainerappgithub-AutoDeployTrigger-55a310a6-aaad-4b00-80fe-6300781a7940.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: democontainerappgithub.azurecr.io
          username: ${{ secrets.DEMOCONTAINERAPPGITHUB_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMOCONTAINERAPPGITHUB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: democontainerappgithub.azurecr.io/democontainerappgithub:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOCONTAINERAPPGITHUB_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n democontainerappgithub -g democontainerappgithub --server democontainerappgithub.azurecr.io --username  ${{ secrets.DEMOCONTAINERAPPGITHUB_REGISTRY_USERNAME }} --password ${{ secrets.DEMOCONTAINERAPPGITHUB_REGISTRY_PASSWORD }}
            az containerapp update -n democontainerappgithub -g democontainerappgithub --image democontainerappgithub.azurecr.io/democontainerappgithub:${{ github.sha }}
